databases:
  - name: BeeHouse
    plan: free
    databaseName: beehouse_db
    user: mysite

services:
  - type: web
    plan: free
    name: BeeHouse
    runtime: python
    buildCommand: './build.sh'
    startCommand: 'python -m gunicorn BeeHouse.asgi:application -k uvicorn.workers.UvicornWorker'
    envVars:
      - key: DATABASE_URL
        fromDatabase:
          name: beehouse_db
          property: connectionString
      - key: SECRET_KEY
        generateValue: true
      - key: WEB_CONCURRENCY
        value: 4
